// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpmFyY8te2MB3XCoThfU_fuwZemysar7I',
    appId: '1:515540863191:web:58963a39aebb8259ee4892',
    messagingSenderId: '515540863191',
    projectId: 'mobo-game-b66c7',
    authDomain: 'mobo-game-b66c7.firebaseapp.com',
    storageBucket: 'mobo-game-b66c7.appspot.com',
    measurementId: 'G-VSW8WWZBKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGvZ36ApWkJhbRHyNvcncYSv91JYK1tFY',
    appId: '1:515540863191:android:43873a3fa3e1b964ee4892',
    messagingSenderId: '515540863191',
    projectId: 'mobo-game-b66c7',
    storageBucket: 'mobo-game-b66c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBdaYacTEAVHVXXGOdHhuW7vpmJRXQEVY',
    appId: '1:515540863191:ios:08a4c5c29cd37690ee4892',
    messagingSenderId: '515540863191',
    projectId: 'mobo-game-b66c7',
    storageBucket: 'mobo-game-b66c7.appspot.com',
    iosBundleId: 'com.example.moboGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBdaYacTEAVHVXXGOdHhuW7vpmJRXQEVY',
    appId: '1:515540863191:ios:78616e1752d9473bee4892',
    messagingSenderId: '515540863191',
    projectId: 'mobo-game-b66c7',
    storageBucket: 'mobo-game-b66c7.appspot.com',
    iosBundleId: 'com.example.moboGame.RunnerTests',
  );
}
